---
version: 1.5
name: osim-rl • Reinforcement learning environments with musculoskeletal models
description: Reinforcement learning environments with musculoskeletal models
url: https://osim-rl.kidzinski.com/
repository: https://github.com/stanfordnmbl/osim-rl
timezone: America/Los_Angeles
twitter:
  username: kidzik
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
    image: "/img/twitter-card.png"
sass:
  style: compressed
exclude:
- ".gitignore"
- CNAME
- icomoon-selection.json
- readme.md
